version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka1:
    image: wurstmeister/kafka:latest
    restart: "no"
    links:
      - zookeeper
    ports:
      - 29092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

    depends_on:
      - zookeeper

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      KAFKA_HOST: kafka1:29092
      # USER_SERVICE_URL: http://user-service:4001
      # USER_SERVICE_URL: localhost:4001
      USER_SERVICE_URL: user-service:4001
    volumes:
      - ./api-gateway:/app
    depends_on:
      - kafka1
    restart: on-failure

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    environment:
      KAFKA_BROKERCONNECT: "kafka1:29092"
    ports:
      - 9000:9000
    depends_on:
      - kafka1

  user-service:
    build: ./user-service
    # ports:
    #   - "4001:4001"

  # mail-service:
  #   build: ./mail-service
  #   environment:
  #     KAFKA_HOST: kafka:9092
  #   depends_on:
  #     - kafka
networks:
  default:
    driver: bridge
